import React from "react";

const Privacy = (props) => {
  return (
    <div
      className="modal fade show"
      id="comply_modal"
      style={{ display: "block" }}
    >
      <div className="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div className="modal-content" style={{ width: "200%" }}>
          <div className="modal-header">
            {/* <h3 className="modal-title d-flex justify-content-center w-100">
              Laboratory safety
            </h3> */}
            <button
              onClick={props.onClose}
              type="button"
              className="close"
              data-dismiss="modal"
            >
              &times;
            </button>
          </div>

          <div className="modal-body pr-3 text-justify">
            Privacy Policy<br></br>
            <ol>
              <li>
                Introduction
                <br></br>
                <span>
                  1.1 We are committed to safeguarding the privacy of our
                  website visitors, service users, individual customers and
                  customer personnel.
                </span>
                <br></br>
                <span>
                  1.2 This policy applies where we are acting as a data
                  controller with respect to the personal data of such persons;
                  in other words, where we determine the purposes and means of
                  the processing of that personal data.
                </span>
                <br></br>
                <span>
                  1.3 Our website incorporates privacy controls which affect how
                  we will process your personal data. By using the privacy
                  controls, you can specify whether you would like to receive
                  direct marketing communications and limit the collection,
                  sharing and publication of your personal data. You can access
                  the privacy controls via [URL].
                </span>
                <br></br>
                <span>
                  1.4 We use cookies on our website. Insofar as those cookies
                  are not strictly necessary for the provision of our website
                  and services, we will ask you to consent to our use of cookies
                  when you first visit our website.
                </span>
                <br></br>
                <span>
                  1.5 In this policy, "we", "us" and "our" refer to [data
                  controller name]. For more information about us, see Section
                  14.
                </span>
                <br></br>
              </li>
              <li>
                The personal data that we collect
                <br></br>
                <span>
                  2.1 In this Section 3 we have set out the general categories
                  of personal data that we process and, in the case of personal
                  data that we did not obtain directly from you, information
                  about the source and specific categories of that data.
                </span>
                <br></br>
                <span>
                  2.2 We may process data enabling us to get in touch with you
                  ("contact data"). The contact data may include your name,
                  email address, telephone number, postal address and/or social
                  media account identifiers. The source of the contact data is
                  you and/or your employer. If you log into our website using a
                  social media account, we will obtain elements of the contact
                  data from the relevant social media account provider.
                </span>
                <br></br>
                <span>
                  2.3 We may process your website user account data ("account
                  data"). The account data may [include your account identifier,
                  name, email address, business name, account creation and
                  modification dates, website settings and marketing
                  preferences. The primary source of the account data is you
                  and/or your employer, although some elements of the account
                  data may be generated by our website. If you log into our
                  website using a social media account, we will obtain elements
                  of the account data from the relevant social media account
                  provider.
                </span>
                <br></br>
                <span>
                  2.4 We may process information relating to transactions,
                  including purchases of goods and/or services, that you enter
                  into with us and/or through our website ("transaction data").
                  The transaction data may include your name, your contact
                  details, your payment card details (or other payment details)
                  and the transaction details. The source of the transaction
                  data is you and/or our payment services provider.
                </span>
                <br></br>
                <span>
                  2.5 We may process information contained in or relating to any
                  communication that you send to us or that we send to you
                  ("communication data"). The communication data may include the
                  communication content and metadata associated with the
                  communication. Our website will generate the metadata
                  associated with communications made using the website contact
                  forms.
                </span>
                <br></br>
                <span>
                  2.6 We may process data about your use of our website and
                  services ("usage data"). The usage data may include your IP
                  address, geographical location, browser type and version,
                  operating system, referral source, length of visit, page views
                  and website navigation paths, as well as information about the
                  timing, frequency and pattern of your service use. The source
                  of the usage data is our analytics tracking system.
                </span>
                <br></br>
                <span>
                  2.7 We may process [identify general category of data]. This
                  data may include [list specific items of data]. The source of
                  this data is [identify source].
                </span>
                <br></br>
              </li>
              <li>
                Purposes of processing and legal bases
                <br></br>
                <span>
                  3.1 In this Section 4, we have set out the purposes for which
                  we may process personal data and the legal bases of the
                  processing.
                </span>
                <br></br>
                <span>
                  3.2 Operations - We may process your personal data for the
                  purposes of operating our website, the processing and
                  fulfilment of orders, providing our services, supplying our
                  goods, generating invoices, bills and other payment-related
                  documentation, and credit control. The legal basis for this
                  processing is our legitimate interests, namely the proper
                  administration of our website, services and business OR the
                  performance of a contract between you and us and/or taking
                  steps, at your request, to enter into such a contract.
                </span>
                <br></br>
                <span>
                  3.3 Publications – Due to privacy and data protection rules
                  and regulations application in the commonwealth of Australia,
                  we will NOT process any account data for purposing of
                  publishing such data on our website and elsewhere through our
                  services.
                </span>
                <br></br>
                <span>
                  3.4 Relationships and communications - We may process contact
                  data, account data, transaction data and/or communication data
                  for the purposes of managing our relationships, communicating
                  with you in order to continue providing support services and
                  complaint handling. The legal basis for this processing is our
                  legitimate interests, namely communications with our website
                  visitors, service users, individual customers and customer
                  personnel, the maintenance of relationships, and the proper
                  administration of our website, services and business.
                </span>
                <br></br>
                <span>
                  3.5 Research and analysis - We may process usage data and/or
                  transaction data for the purposes of researching and analysing
                  the use of our website and services, as well as researching
                  and analysing other interactions with our business. The legal
                  basis for this processing is consent OR our legitimate
                  interests, namely monitoring, supporting, improving and
                  securing our website, services and business generally.
                </span>
                <br></br>
                <span>
                  3.6 Record keeping - We may process your personal data for the
                  purposes of creating and maintaining our databases, back-up
                  copies of our databases and our business records generally.
                  The legal basis for this processing is our legitimate
                  interests, namely ensuring that we have access to all the
                  information we need to properly and efficiently run our
                  business in accordance with this policy.
                </span>
                <br></br>
                <span>
                  3.7 Security - We may process your personal data for the
                  purposes of security and the prevention of fraud and other
                  criminal activity. The legal basis of this processing is our
                  legitimate interests, namely [the protection of our website,
                  services and business, and the protection of others.
                </span>
                <br></br>
                <span>
                  3.8 Insurance and risk management - We may process your
                  personal data where necessary for the purposes of obtaining or
                  maintaining insurance coverage, managing risks and/or
                  obtaining professional advice. The legal basis for this
                  processing is our legitimate interests, namely the proper
                  protection of our business against risks.
                </span>
                <br></br>
                <span>
                  3.9 Legal claims - We may process your personal data where
                  necessary for the establishment, exercise or defence of legal
                  claims, whether in court proceedings or in an administrative
                  or out-of-court procedure. The legal basis for this processing
                  is our legitimate interests, namely the protection and
                  assertion of our legal rights, your legal rights and the legal
                  rights of others.
                </span>
                <br></br>
                <span>
                  3.10 Legal compliance and vital interests - We may also
                  process your personal data where such processing is necessary
                  for compliance with a legal obligation to which we are subject
                  or in order to protect your vital interests or the vital
                  interests of another natural person.
                </span>
                <br></br>
              </li>
              <li>
                Providing your personal data to others
                <br></br>
                <span>
                  4.1 Your personal data held in our website database will be
                  stored on the servers of our hosting services providers being
                  AWS (Amazon Workspace) likewise being located at amazon
                </span>
                <br></br>
                <span>
                  4.2 Financial transactions relating to our website and
                  services are OR may be handled by our payment services
                  providers, [identify PSPs]. We will share transaction data
                  with our payment services providers only to the extent
                  necessary for the purposes of processing your payments,
                  refunding such payments and dealing with complaints and
                  queries relating to such payments and refunds]. You can find
                  information about the payment services providers' privacy
                  policies and practices at [URLs].
                </span>
                <br></br>
                <span>
                  4.3 In addition to the specific disclosures of personal data
                  set out in this Section 5, we may disclose your personal data
                  where such disclosure is necessary for compliance with a legal
                  obligation to which we are subject, or in order to protect
                  your vital interests or the vital interests of another natural
                  person. We may also disclose your personal data where such
                  disclosure is necessary for the establishment, exercise, or
                  defence of legal claims, whether in court proceedings or in an
                  administrative or outof-court procedure
                </span>
                <br></br>
              </li>
              <li>
                International transfers of your personal data
                <br></br>
                <span>
                  5.1 In this Section 6, we provide information about the
                  circumstances in which your personal data may be transferred
                  to countries outside the Commonwealth of Australia.
                </span>
                <br></br>
                <span>
                  5.2 The hosting facilities for our website are situated in the
                  Commonwealth of Australia. The competent data protection
                  authorities have made an "adequacy decision" with respect to
                  the data protection laws of Australia. Transfers to second or
                  third jurisdictions or countries will be protected by
                  appropriate safeguards, namely the use of standard data
                  protection clauses adopted or approved by the competent data
                  protection authorities.
                </span>
                <br></br>
                <span>
                  5.3 You acknowledge that personal data that you submit for
                  publication through our website or services may be available,
                  via the internet, around the world. We cannot prevent the use
                  (or misuse) of such personal data by others.
                </span>
                <br></br>
              </li>
              <li>
                Retaining and deleting personal data
                <br></br>
                <span>
                  6.1 This Section 7 sets out our data retention policies and
                  procedures, which are designed to help ensure that we comply
                  with our legal obligations in relation to the retention and
                  deletion of personal data.
                </span>
                <br></br>
                <span>
                  6.2 Personal data that we process for any purpose or purposes
                  shall not be kept for longer than is necessary for that
                  purpose or those purposes.
                </span>
                <br></br>
                <span>
                  6.3 We will retain your personal data as follows:
                  <br></br>
                  <span className="ml-4">
                    (a) contact data will be retained for a minimum period of 12
                    weeks following the date of the most recent contact between
                    you and us, and for a maximum period of 12 weeks following
                    that date;
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (b) account data will be retained for a minimum period of 12
                    weeks following the date of closure of the relevant account,
                    and for a maximum period of 12 weeks following that date;
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (c) transaction data will be retained for a minimum period
                    of 12 weeks following the date of the transaction, and for a
                    maximum period of 12 following that date;
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (d) communication data will be retained for a minimum period
                    of 12 weeks following the date of the communication in
                    question, and for a maximum period of 12 weeks following
                    that date;{" "}
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (e) usage data will be retained for 12 weeks following the
                    date of collection; and
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (f) Specific individual OR personal user data will be
                    retained for a minimum period of 12 weeks following [date],
                    and for a maximum period of 12 weeks following [date].
                  </span>
                  <br></br>
                </span>
                <span>
                  6.4 Notwithstanding the other provisions of this Section 7, we
                  may retain your personal data where such retention is
                  necessary for compliance with a legal obligation to which we
                  are subject, or in order to protect your vital interests or
                  the vital interests of another natural person.
                </span>
                <br></br>
              </li>
              <li>
                Your rights
                <br></br>
                <span>
                  7.1 In this Section 8, we have listed the rights that you have
                  under data protection law.
                </span>
                <br></br>
                <span>
                  7.2 Your principal rights under data protection law are:
                  <br></br>
                  <span>
                    (a) the right to access - you can ask for copies of your
                    personal data;
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (b) the right to rectification - you can ask us to rectify
                    inaccurate personal data and to complete incomplete personal
                    data;
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (c) the right to erasure - you can ask us to erase your
                    personal data;
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (d) the right to restrict processing - you can ask us to
                    restrict the processing of your personal data;
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (e) the right to object to processing - you can object to
                    the processing of your personal data;
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (f) the right to data portability - you can ask that we
                    transfer your personal data to another organisation or to
                    you;
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (g) the right to complain to a supervisory authority - you
                    can complain about our processing of your personal data; and
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (h) the right to withdraw consent - to the extent that the
                    legal basis of our processing of your personal data is
                    consent, you can withdraw that consent
                  </span>
                  <br></br>
                </span>
                <span>
                  7.3 These rights are subject to certain limitations and
                  exceptions as define by applicable{" "}
                </span>
                <br></br>
                <span>
                  7.4 You may exercise any of your rights in relation to your
                  personal data by written notice to us, using the contact
                  details set out below.
                </span>
                <br></br>
              </li>
              <li>
                About cookies
                <br></br>
                <span>
                  8.1 A cookie is a file containing an identifier (a string of
                  letters and numbers) that is sent by a web server to a web
                  browser and is stored by the browser. The identifier is then
                  sent back to the server each time the browser requests a page
                  from the server
                </span>
                <br></br>
                <span>
                  8.2 Cookies may be either "persistent" cookies or "session"
                  cookies: a persistent cookie will be stored by a web browser
                  and will remain valid until its set expiry date, unless
                  deleted by the user before the expiry date; a session cookie,
                  on the other hand, will expire at the end of the user session,
                  when the web browser is closed.
                </span>
                <br></br>
                <span>
                  8.3 Cookies may not contain any information that personally
                  identifies a user, but personal data that we store about you
                  may be linked to the information stored in and obtained from
                  cookies.
                </span>
                <br></br>
              </li>
              <li>
                Cookies that we use
                <br></br>
                <span>
                  9.1 We use cookies for the following purposes:
                  <br></br>
                  <span className="ml-5">
                    (a) authentication and status - we use cookies to identify
                    you when you visit our website and as you navigate our
                    website, and to help us determine if you are logged into our
                    website.
                  </span>
                  <span className="ml-5"></span>
                  <br></br>
                  <span className="ml-5">
                    (b) service purchase - we use cookies to maintain the state
                    of your services purchased as you navigate our website.
                  </span>
                  <br></br>
                  <span className="ml-5">
                    (c) personalisation - we use cookies to store{" "}
                  </span>
                  <br></br>
                  <span className="ml-5">
                    (d) security - we use cookies as an element of the security
                    measures used to protect user accounts, including preventing
                    fraudulent use of login credentials, and to protect our
                    website and services generally.
                  </span>
                  <br></br>
                  <span className="ml-5">
                    (e) advertising - we use cookies to help us to display
                    advertisements that will be relevant to you.
                  </span>
                  <br></br>
                  <span className="ml-5">
                    (f) analysis - we use cookies to help us to analyse the use
                    and performance of our website and services.
                  </span>
                  <br></br>
                </span>
              </li>
              <li>
                Cookies used by our service providers
                <br></br>
                <span>
                  10.1 Our service providers use cookies and those cookies may
                  be stored on your computer when you visit our website.
                </span>
                <br></br>
                <span></span>
                <span>
                  10.2 We use Google Analytics. Google Analytics gathers
                  information about the use of our website by means of cookies.
                  The information gathered is used to create reports about the
                  use of our website. You can find out more about Google's use
                  of information by visiting
                  https://www.google.com/policies/privacy/partners/ and you can
                  review Google's privacy policy at
                  https://policies.google.com/privacy.
                </span>
                <br></br>
              </li>
              <li>
                Managing cookies
                <br></br>
                <span>
                  11.1 Most browsers allow you to refuse to accept cookies and
                  to delete cookies. The methods for doing so vary from browser
                  to browser, and from version to version. You can however
                  obtain up-to-date information about blocking and deleting
                  cookies via these links:
                  <br></br>
                  <span className="ml-4">
                    (a) https://support.google.com/chrome/answer/95647 (Chrome);
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (b)
                    https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-websitepreferences
                    (Firefox);
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (c) https://help.opera.com/en/latest/security-and-privacy/
                    (Opera);
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (d)
                    https://support.microsoft.com/en-gb/help/17442/windows-internet-explorerdelete-manage-cookies
                    (Internet Explorer);
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (e)
                    https://support.apple.com/en-gb/guide/safari/manage-cookies-and-websitedata-sfri11471/mac
                    (Safari); and
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (f)
                    https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy
                    (Edge).
                  </span>
                </span>
                <br></br>
                <span>
                  11.2 Blocking all cookies will have a negative impact upon the
                  usability of many websites.
                </span>
                <br></br>
                <span>
                  11.3 If you block cookies, you will not be able to use all the
                  features on our website.
                </span>
                <br></br>
              </li>
              <li>
                Amendments
                <br></br>
                <span>
                  12.1 We may update this policy from time to time by publishing
                  a new version on our website.
                </span>
                <br></br>
                <span>
                  12.2 You should check this page occasionally to ensure you are
                  happy with any changes to this policy.
                </span>
                <br></br>
                <span>
                  12.3 We may OR will notify you of changes OR significant
                  changes to this policy by email.
                </span>
                <br></br>
              </li>
              <li>
                Our details
                <br></br>
                <span>
                  13.1 This website is owned and operated by VirtuPharma Pty
                  Ltd.
                </span>
                <br></br>
                <span>
                  13.2 We are registered in the Commonwealth of Australia under
                  registration number ABN: 37626248208, and our registered offi
                </span>
                <br></br>
                <span>
                  13.3 Our principal place of business is at Sydney Knowledge
                  Hub, Merewether Building, H04, Level 2, 2006, NSW.{" "}
                </span>
                <br></br>
                <span>
                  13.4 You can contact us:
                  <br></br>
                  <span className="ml-4">
                    (a) by post, to the postal address given above;
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (b) using our website contact form;
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (c) by telephone (Mob: 0404789778), or the contact number (2
                    8052 3988) published on our website; or
                  </span>
                  <br></br>
                  <span className="ml-4">
                    (d) by email, using info@virtupharma.com.au the email
                    address published on our website
                  </span>
                  <br></br>
                </span>
                <br></br>
              </li>
            </ol>
          </div>
          <div className="modal-footer">
            <button
              type="button"
              className="btn btn-secondary"
              data-dismiss="modal"
              onClick={props.onClose}
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
