export const SET_LOGGEDIN_STATUS = "SET_LOGGEDIN_STATUS";

export const SET_TOAST_SUCCESS = "SET_TOAST_SUCCESS";
export const SET_TOAST_FAIL = "SET_TOAST_FAIL";
export const SET_TOAST_WARNING = "SET_TOAST_WARNING";
export const SET_TOAST_INFO = "SET_TOAST_INFO";
export const RESET_TOAST = "RESET_TOAST";

export const SET_LOADER_DISPLAY = "SET_LOADER_DISPLAY";

export const SET_CASES_ARRAY = "SET_CASES_ARRAY";

export const SET_IMAGE_ADDED_STATUS = "SET_IMAGE_ADDED_STATUS";
export const SET_IMAGES_BY_CASE_ID = "SET_IMAGES_BY_CASE_ID";
export const SET_IMAGE_REMOVED_STATUS = "SET_IMAGE_REMOVED_STATUS";

export const SET_QUESTION_IMAGES = "SET_QUESTION_IMAGES";