import React from 'react'

function TeachLabwork() {
    return (
        <main>
  <div id="fb-root" />
  <div className="blog-single-banner">
    <img src="https://virtupharma.com.au/storage/blog/33/1603178623219850843.png" alt="Yet another successful trial of the VirtuPharma Labs" className="w-100 img-fluid" height={571} />
  </div>
  <div className="blog-content">
    <div className="date">Oct 20, 2020</div>
    <div className="title">Yet another successful trial of the VirtuPharma Labs</div>
    <div className="blog-text">
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>In line with our commitment to ensuring unhindered access to state-of-the-art scientific and educational lab facilities irrespective of location, we are pleased to inform you of a successful trial in our Virtual Pharmaceutical Laboratory.</span></span></span></span></span></span></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>At VirtuPharma, we believe that with the right effective teaching and instruction methods, there are no limits to what we can achieve in science. Lab technicians, chemists, pathologist departments, and even students are all adversely affected by the unavailability of sophisticated facilities, such as laboratories and advanced equipment. </span></span></span></span></span></span></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>Therefore, we were delighted to trial our laboratory with the Pharmacy Faculty of the University of Sydney to take yet another vital step forward on our journey to make remote lab access to students to experience test instruments and equipment. </span></span></span></span></span></span></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}>&nbsp;</p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><strong><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>What this success means...</span></span></span></span></span></span></strong></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>This successful trial has quelled the stemming doubts about the feasibility of a cloud-based world-class virtual pharmaceutical laboratory running at full capacity.</span></span></span></span></span></span></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>For us at VirtuPharma, it is in line with our vision of serving the purpose of science and engineering education, using expensive and effective tools that are only found in a few top institutions across the world. </span></span></span></span></span></span></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>We have always wanted to provide individual real-world lab job settings, equipment, and experience to individuals passionate about science and laboratory. The team of students from the Faculty Pharmacy of the University of Sydney helped us achieve this. </span></span></span></span></span></span></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}>&nbsp;</p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><strong><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>We can do more...</span></span></span></span></span></span></strong></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>The issue of inadequate experimental training has lingered in our educational system for a long time. Universities have struggled to provide the necessary facilities to make this happen. We recognize this problem, and we have the perfect solution - the VirtuPharma cloud-based science laboratories. </span></span></span></span></span></span></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>At VirtuPharma, we are confident that our cloud-based laboratories operating within regulatory accreditation are the lasting solution to the problem of scarce educational and scientific resources. We want to give unrestricted access to complex lab instruments to facilitate individual learning in the field of science. </span></span></span></span></span></span></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>This successful student collaboration has shown our readiness to eliminate the time and location limitations faced by traditional workgroups. Students can now engage in learning and work on life-changing projects at any moment and from anywhere, using our world-class virtual laboratory facilities and gaining </span></span></span><span lang="EN-GB" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>personalised training on such costly instruments as:</span></span></span> </span></span></span></p>
      <ul>
        <li style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', margin: '0cm 0cm 0cm 36pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>HPLC-MS</span></span></span></span></span></span></li>
        <li style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', margin: '0cm 0cm 0cm 36pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>HPLC-PDA</span></span></span></span></span></span></li>
        <li style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', margin: '0cm 0cm 0cm 36pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>GC-UV</span></span></span></span></span></span></li>
        <li style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', margin: '0cm 0cm 8pt 36pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>UV-Vis</span></span></span></span></span></span></li>
      </ul>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>24/7 access to equipment and working with top scientists in real-time will also expose students to practical lab skills, an integral aspect of learning that is almost non-existent in the university curriculum. You are always in safe hands with our team of experienced and qualified lab experts who are ready to help you get the best out of these opportunities. </span></span></span></span></span></span></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}>&nbsp;</p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><strong><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>Let's work together. </span></span></span></span></span></span></strong></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>Are you ready to teach what you know or showcase your solutions as a scientist? Our interactive training platform is just for you. </span></span></span></span></span></span></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>If you are a scientist, upload your videos or remotely use our instruments and teach to earn. You can also upload your scientific papers to our Forum and promote your research.</span></span></span></span></span></span></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-US" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}>At VirtuPharma, we are always delighted to work with you. Contact us through any of our communication lines today, and we will take it from there.</span></span></span></span></span></span></p>
      <p style={{marginTop: '12.0pt', marginRight: '0cm', marginBottom: '0cm', marginLeft: '0cm', margin: '0cm 0cm 8pt'}}><span style={{fontSize: '11pt'}}><span style={{lineHeight: '107%'}}><span style={{fontFamily: 'Calibri,sans-serif'}}><span lang="EN-GB" style={{fontSize: '12.0pt'}}><span style={{lineHeight: '107%'}}><span arial style={{fontFamily: ''}}><a href="mailto:info@virtupharma.com.au" style={{color: '#0563c1', textDecoration: 'underline'}}>info@virtupharma.com.au</a></span></span></span> </span></span></span></p>
      <div className="author d-flex align-items-sm-center flex-sm-row flex-column align-items-start">
        <img src="https://virtupharma.com.au/storage/blog/33/1603178623363876533.png" alt="author" />
        <table>
          <tbody>
            <tr>
              <td>Author</td>
              <td>VirtuPharma</td>
            </tr>
            <tr>
              <td>Published</td>
              <td>Oct 20, 2020</td>
            </tr>
            <tr>
              <td>Last updated</td>
              <td>Oct 20, 2020</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div className="fb-comments" data-href="https://virtupharma.com.au/forum/teach-labwork" data-width="100%" data-numposts={10} />
  </div>
</main>

    )
}

export default TeachLabwork
